### ISSUE TITLE
Meta data for result detail page

### ISSUE THREAD

**Issue by mickbut-ler** [viral-finder/social-finder#2]
After sorting al the data the script must collect the following data: 

Likes: 
- [ ] most per post
- [ ] Average
- [ ] Total 

Comments: 
- [ ] most per post
- [ ] Average
- [ ] Total 

Engagement: 
- [ ] most per post
- [ ] Average
- [ ] Total 

Make a selection of most used hashtags 

make a selection of most mentioned users 

![Image](https://github.com/viral-finder/social-finder/assets/80526334/650b2848-87c0-4acd-bc26-e575432914e8)
